In [ ]:
#1. What is a Python library? Why  we use Python libraries?
"""Python libraries are collections of reusable code modules that you can integrate into your projects to save time and effort. 
 They are like a toolbox, each providing different tools that can be used to perform various tasks efficiently"""
#Use of python Libraries ------->
"""As we write large-size programs in Python, we want to maintain the code’s modularity.
For the easy maintenance of the code, we split the code into different parts and we can use that code later ever we need it.
In Python, modules play that part. Instead of using the same code in different programs and making the code complex, 
we define mostly used functions in modules and we can just simply import them in a program wherever there is a requirement.
We don’t need to write that code but still, we can use its functionality by importing its module.
Multiple interrelated modules are stored in a library. And whenever we need to use a module, we import it from its library.
In Python, it’s a very simple job to do due to its easy syntax. We just need to use import."""
#Let’s have a look at some of the commonly used libraries:------>
"""1.Numpy:----> The name “Numpy” stands for “Numerical Python”. It is the commonly used library. 
It is a popular machine learning library that supports large matrices and multi-dimensional data. 
It consists of in-built mathematical functions for easy computations.

2.Matplotlib:---> This library is responsible for plotting numerical data. And that’s why it is used in data analysis.
It is also an open-source library and plots high-defined figures like pie charts, histograms, scatterplots, graphs, etc.

3.Pandas:---> Pandas are an important library for data scientists. It is an open-source machine learning library that provides flexible high-level data structures and a variety of analysis tools.
It eases data analysis, data manipulation, and cleaning of data. Pandas support operations like Sorting, Re-indexing, Iteration, Concatenation, Conversion of data, Visualizations, Aggregations,etc

4.SciPy:---> The name “SciPy” stands for “Scientific Python”. It is an open-source library used for high-level scientific computations.

5.PyBrain: The name “PyBrain” stands for Python Based Reinforcement Learning, Artificial Intelligence, and Neural Networks library. """

#2.2. What is the difference between Numpy array and List?
"""Numpy Array                                                           |	Python List
It is the core Library of python which is used for scientific computing. |	The core library of python provides list.
It can contain similar datatypes.	                                     |  It Contains different types of datatypes.
We need to Numpy Library to access Numpy Arrays.	                     |  It is built-in function of python.
It is Homogeneous.	                                                     |  It is both homogeneous and heterogeneous.
In this Element wise operation is possible.                              |	Element wise operation is not possible on the list.
By using numpy.array() we can create N-Dimensional array.                |	It is by default 1-dimensional.In some cases, we can 
                                                                         |    create an N-Dimensional list. But it is a long process.
It requires smaller memory consumption as compared to Python List.	     |  It requires more memory as compared to Numpy Array.
In this each item is stored in a sequential manner.                      |	It stores item in random location of  the memory.
It is faster as compared to list.	                                     |  It is slow as compared to NumPy Array.
It also have some optimism function .	                                 |  It does not have some optimism function ."""
    
    
    

In [ ]:
import numpy as nc

In [11]:
"""3. Find the shape, size and dimension of the following array?"""
arr=nc.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr.shape)
print(arr.size)
print(arr.ndim)


(3, 4)
12
2


In [12]:
"""4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]"""
arr1=nc.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print(arr1[0])



[1 2 3 4]


In [13]:
"""5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]"""
arr=nc.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [15]:
type(arr)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr[2][3]

12

In [16]:
arr.ndim

2

In [10]:
"""6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]"""

import numpy as nc
arr=nc.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
odd = arr[:, 1::2]
print(odd)#print all odd indexed elements

[[ 2  4]
 [ 6  8]
 [10 12]]


In [104]:
import numpy as nc
import random
"7. How can you generate a random 3x3 matrix with values between 0 and 1?"
x= nc.random.uniform(0, 1 , size=(3,3))
x

array([[0.73429145, 0.69851141, 0.19523353],
       [0.35460142, 0.20333695, 0.28964155],
       [0.63670927, 0.68356782, 0.77848405]])

In [ ]:
"""8. Describe the difference between np.random.rand and np.random.randn?"""
#The numpy.random.rand() generates random values in a given shape. It creates an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
#On the other hand, numpy.random.random() return random floats in the half-open interval [0.0, 1.0).

#Both functions generate samples from the uniform distribution on [0, 1). The only difference is in how the arguments are handled.
#example----------------------->

In [142]:
A=nc.random.rand(2,5)  # it shows value  between 0 and 1 , all values genrated by rand is +ve
A

array([[0.1741245 , 0.78016627, 0.9957118 , 0.95674522, 0.17140624],
       [0.31133672, 0.84487602, 0.3836483 , 0.01059885, 0.92345017]])

In [143]:
B=nc.random.randn(2,5)  #here randn generate  -ve values  also
B

array([[ 1.26505239,  1.02767739,  1.45395593, -1.58161744, -0.4039556 ],
       [ 0.08444009,  0.95155732,  0.54341459, -0.66062749, -1.93868295]])

In [8]:
"""9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]"""
import numpy as nc
arry=nc.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arry
nc.ndim(arry)


2

In [13]:
arry=nc.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]])
nc.ndim(arry)  # by adding a square bracket in given array dimension is increased

3

In [23]:
arry.shape

(1, 3, 4)

In [18]:
x=nc.expand_dims(arry,axis=0) # here we increase the dimension by using expan-_dim()function ,here axis=0 is-x axis

In [20]:
print(x)

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]]


In [19]:
nc.ndim(x)

4

In [22]:
x.shape

(1, 1, 3, 4)

In [24]:
"""10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]"""
arry1=nc.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arry1


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
arry1.T #using .T for transpose

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [29]:
"""11. Consi^er the following matrix:
Matrix A [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
1.index wise multiplication
2.matrix multipication
3.add both matrix
4.subtract matrix B by A
5. divide matrix B by A"""
A=nc.matrix([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B=nc.matrix([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])


In [30]:
A #(3*4)

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [31]:
B #(3*4)

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [58]:
C=B.T #here transpose the matrix B because for matrix multiplication of size( m*n ) and (p*q) here n must be equals to p
print(C)  #(4*3) 

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [59]:
A @ C #Matrix multiplication

matrix([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

In [53]:
nc.shape(A)

(3, 4)

In [45]:
nc.ndim(A)

2

In [34]:
nc.multiply(A,B)#index wise multiplication

matrix([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]])

In [38]:
A+B #matrix addition

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

In [39]:
B-A #matrix subtraction

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [40]:
B/A #divide matrix B by A

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [78]:
b=nc.array([1,3,4,5])
b

array([1, 3, 4, 5])

In [129]:
"""12.  Which function in Numpy can be used to swap the byte order of an array?"""
#“byteswap()”, function is used to swap the bytes.
A = nc.array([1, 256, 87],dtype= nc.int16)
A

array([  1, 256,  87], dtype=int16)

In [130]:
A.byteswap(inplace=True)

array([  256,     1, 22272], dtype=int16)

In [112]:
"""13.What is the significance of the np.linalg.inv function?"""
#We use numpy.linalg.inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results inidentity matrix.
X=nc.matrix([[2,4],[5,6]])
print("orignal matrix",X)


orignal matrix [[2 4]
 [5 6]]


In [113]:
Y = nc.linalg.inv(X)
print("after inverse",Y)

after inverse [[-0.75   0.5  ]
 [ 0.625 -0.25 ]]


In [85]:
"""14. What does the np.reshape function do, and how is it used?"""
#Reshaping numpy array simply means changing the shape of the given array, shape basically tells the number of elements and dimension of array,
#by reshaping an array we can add or remove dimensions or change number of elements in each dimension.
sh=nc.arange(12)
sh

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [90]:
print(sh.ndim)

1


In [91]:
sh.shape

(12,)

In [98]:
x=nc.reshape(sh,(2,2,3))
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [99]:
x.ndim

3

In [101]:
x2=nc.reshape(sh,(3,2,2))
x2

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [102]:
x2.ndim

3

In [105]:
x3=nc.reshape(sh,(1,3,4))
x3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [75]:
"""15. What is broadcasting in Numpy?"""
#broadcasting refers to how NumPy treats arrays with different dimensions during arithmetic operations which lead to certain constraints,
#the smaller array is broadcast across the larger array so that they have compatible shapes.
abrod=nc.zeros((3,4),int)
print(abrod)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [79]:
abrod+b #here array b is broadcast to array abrod

array([[1, 3, 4, 5],
       [1, 3, 4, 5],
       [1, 3, 4, 5]])